python train.py \
--label 'Serifs' \
--model 'efficientnet_b0' \
--train_folder '../serif_dataset/train' \
--test_folder '../serif_dataset/test' \
--base_lr 0.01 \
--epochs 30 \
--batch_size 32 \
--gamma 0.2 \
--step 5 \
--gpu 0 \
--seed 50 \
--num_workers 8